### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by horta** [paradoxxxzero/atom-python-import-magic#1]
Hello,

Thanks a lot for the package =)

I can't use it on Python 2.7 though because of

```
Python Import Magic Invocation Error
Traceback (most recent call last):
  File "/Users/horta/.atom/packages/python-import-magic/lib/import_magic_interface.py", line 5, in <module>
    from itertools import accumulate, chain
ImportError: cannot import name accumulate
```

Are you planning to support Python 2.7?

**Comment by byteknacker** [comment]
Same issue here @Horta I am also using Python 2.7 for this plugin and the newest Atom release as of today.

**Comment by paradoxxxzero** [comment]
Could you try the 0.11.0 version? (Sorry for the delay I kind of missed theses issues.)
