### ISSUE TITLE
plugin shouldn't be running pip

### ISSUE THREAD

**Issue by leos** [paradoxxxzero/atom-python-import-magic#3]
I understand what you're going for with having the plugin automatically install its own dependencies  [here](https://github.com/paradoxxxzero/atom-python-import-magic/blob/master/lib/import_magic_interface.py#L38-L49) - but this is really unexpected behavior for a plugin and can create issues for people.

In my situation, I have systemwide pip blocked to prevent me from accidentally using it without a virtualenv. This code tries to run when Atom starts up and before it has opened the project and picked the right python binary. This means I get an error in [read_index](https://github.com/paradoxxxzero/atom-python-import-magic/blob/master/lib/import_magic_interface.py#L82) (which is called from \_\_init__ ) because importmagic is still None.

Once the project is loaded up, the plugin gets invoked with the proper interpreter but there's still that error on startup. Going back to the root issue, I wouldn't want an Atom plugin automatically doing anything with pip for me.

**Comment by paradoxxxzero** [comment]
I recently removed this feature, when dependencies are not installed you get a notification instead.

**Comment by leos** [comment]
Awesome, thank you!
